// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBR6BNv2p1rDYHrPQMVeWP7p6q6SGOYAk',
    appId: '1:795728316104:web:417e4b78e4a067113c07fd',
    messagingSenderId: '795728316104',
    projectId: 'moviemaze-app',
    authDomain: 'moviemaze-app.firebaseapp.com',
    storageBucket: 'moviemaze-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1GoafccnF1Zd1WovRzZ1TTFEFSeZbMqc',
    appId: '1:795728316104:android:c224439e3ddf66443c07fd',
    messagingSenderId: '795728316104',
    projectId: 'moviemaze-app',
    storageBucket: 'moviemaze-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf8smrudDOeW6m6qpaqkWrMiwHXnp6gLU',
    appId: '1:795728316104:ios:f6d40190104466c73c07fd',
    messagingSenderId: '795728316104',
    projectId: 'moviemaze-app',
    storageBucket: 'moviemaze-app.firebasestorage.app',
    iosBundleId: 'com.example.moviemazeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf8smrudDOeW6m6qpaqkWrMiwHXnp6gLU',
    appId: '1:795728316104:ios:f6d40190104466c73c07fd',
    messagingSenderId: '795728316104',
    projectId: 'moviemaze-app',
    storageBucket: 'moviemaze-app.firebasestorage.app',
    iosBundleId: 'com.example.moviemazeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBR6BNv2p1rDYHrPQMVeWP7p6q6SGOYAk',
    appId: '1:795728316104:web:dcc0bec20c3bb59a3c07fd',
    messagingSenderId: '795728316104',
    projectId: 'moviemaze-app',
    authDomain: 'moviemaze-app.firebaseapp.com',
    storageBucket: 'moviemaze-app.firebasestorage.app',
  );
}
